name: learn-github-actions # The name displayed in the GitHub Actions tab

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest # где запускаем
    steps: # что делаем
      - uses: actions/checkout@v5 # выкачиваем репозиторий
      - uses: actions/setup-java@v5 # настраиваем Java
        with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '21'
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - run: ./gradlew clean test -Dselenide.remote=https://your.selenoid.com:4444/wd/hub # запускаем тесты